before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: rt-retention
    tap:
      owner: verifa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/verifa/rt-retention"
    description: "Artifactory Retention"
    test: |
      system "#{bin}/rt-retention -v"

dockers:
  - goos: linux
    goarch: amd64
    skip_push: "false"
    use: buildx
    dockerfile: Dockerfile
    image_templates:
      - "verifa/{{ .ProjectName }}:latest"
      - "verifa/{{ .ProjectName }}:{{ .Tag }}"
      - "verifa/{{ .ProjectName }}:{{ .Major }}"
      - "verifa/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "verifa/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
      - "--pull"

release:
  github:
    owner: verifa
    name: rt-retention
  prerelease: auto
  disable: false
  draft: false
