site_name: Artifactory Retention
site_url: https://rt-retention.verifa.io
site_description: >-
  JFrog CLI plugin for facilitating Artifactory retention policies

# Repository
repo_name: verifa/rt-retention
repo_url: https://github.com/verifa/rt-retention

# Copyright
copyright: Copyright &copy; 2022 Verifa

# Theme
theme:
  name: material

  font:
    text: Outfit
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - toc.follow

# Plugins
plugins:
  - awesome-pages
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/verifa

extra_css:
  - stylesheets/theme.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - meta
  - toc:
      permalink: true
